/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tetras;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ExceptionsTest {

    @Test
    public void testGood() {

        RequeteHttp Reqtest = new RequeteHttp();
        Reqtest.ajouter(new URL("/good.com"));
        //Reqtest.ajouter(new Header("LE","GOOD"));
        //Reqtest.ajouter(new Body("EssaiurlGood"));
        ServeurWeb srv = new ServeurWeb();

        assertEquals(200, srv.repondre(Reqtest));
    }

    @Test
    public void testNull() {
        RequeteHttp Reqtest = new RequeteHttp();
        Reqtest.ajouter(new URLNull("")); 
        //Reqtest.ajouter(new Header("LE","NULL"));
        //Reqtest.ajouter(new Body("EssaiurlNull"));
        ServeurWeb srv = new ServeurWeb();

        assertEquals(500, srv.repondre(Reqtest));
    }
    
    @Test
    public void testDanger() {
        RequeteHttp Reqtest = new RequeteHttp();
        Reqtest.ajouter(new URLDangereux("/danger.com"));
        //Reqtest.ajouter(new Header("LE","DANGER"));
        //Reqtest.ajouter(new Body("EssaiurlDanger"));
        ServeurWeb srv = new ServeurWeb();

        assertEquals(403, srv.repondre(Reqtest));
    }
}
